conciergerie/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

# --- Import de vos ViewSets ---
from conciergerie.api_views import (
    PropertyViewSet, ReservationViewSet, ServiceTaskViewSet,
    IncidentViewSet, AdditionalExpenseViewSet, EmployeeViewSet
)
from conciergerie.reporting_views import (
    RevenueReportView, PropertyRevenueMonthlyView,
    OccupancyRateView, FinancialPDFReportView
)

# --- Pour les utilisateurs ---
from django.contrib.auth import get_user_model
from rest_framework import viewsets, serializers
## webhooks OTA
from conciergerie.api_views_period import ReservationPeriodAPIView, ServiceTaskPeriodAPIView
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from conciergerie.reporting_views import (
    RevenueReportPDFView,
    PropertyRevenueMonthlyPDFView,
    OccupancyRatePDFView,
)
from conciergerie.ota_views import airbnb_webhook, booking_webhook
from conciergerie import views as co_views
from conciergerie import api_views_dashboard as co_api_dashboard
from conciergerie import api_views as co_api_views
# api_reporting_views
from conciergerie import api_reporting_views as api_report
from core.api.views import LandingSectionPublicViewSet

app_name = "conciergerie"

# Serializer simple pour User
class UserSerializer(serializers.ModelSerializer):
    class Meta:
        model = get_user_model()
        fields = ["id", "username", "email", "first_name", "last_name"]

# ViewSet User
class UserViewSet(viewsets.ModelViewSet):
    queryset = get_user_model().objects.all()
    serializer_class = UserSerializer


# --- Router DRF ---
router = DefaultRouter()
router.register(r'properties', PropertyViewSet, basename="property")
router.register(r'reservations', ReservationViewSet, basename="reservation")
router.register(r'tasks', ServiceTaskViewSet, basename="task")
router.register(r'incidents', IncidentViewSet, basename="incident")
router.register(r'expenses', AdditionalExpenseViewSet, basename="expense")
router.register(r'employees', EmployeeViewSet, basename="employee")
router.register(r'users', UserViewSet, basename="user")
router.register(r"public/landing", LandingSectionPublicViewSet, basename="public-landing")


# --- URL patterns ---
urlpatterns = [
    
    path("home_public/", co_views.HomePublicView.as_view(), name="home_public"),
    path("dashboard/", co_views.home, name="dashboard"),
    path("home/", co_views.conciergerie_page , name="home"),
    path('property/', co_views.PropretyList.as_view(), name='property_list'),
    path('show/<int:pk>/', co_views.PropertyDetail.as_view(), name='property_detail'),
    path('resa/<int:reservation_id>/show/', co_views.details_reservation, name='checkin_detail'),
    path('resa/<int:resa>/show/', co_views.details_reservation, name='checkin_detail'),
    path('property/<int:property_id>/show/', co_views.property_details_plus, name='property_details_plus'),
    ## reprt 
    path('property/<int:property_id>/report/', co_views.property_report, name='property_report'),

    # API métiers
    path("api/", include(router.urls)),

    # api properties
    path("api/properties/myagency/", PropertyViewSet.as_view({'get': 'mine'}), name="property-my_agency"),

    # Auth JWT
    path("api/auth/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/auth/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),

    # Reporting
    path("api/reports/revenue/", RevenueReportView.as_view(), name="revenue-report"),
    path("api/reports/property/<int:property_id>/monthly-revenue/", PropertyRevenueMonthlyView.as_view(),
         name="property-monthly-revenue"),
    path("api/reports/property/<int:property_id>/occupancy/", OccupancyRateView.as_view(), name="occupancy-rate"),
    path("api/reports/pdf/", FinancialPDFReportView.as_view(), name="financial-pdf"),
    ##
    path("api/financial-reports/", api_report.FinancialReportSummaryView.as_view(), name="financial-report-summary"),
]

## generer rapport pdf 

urlpatterns += [
    path("api/reports/revenue/pdf", RevenueReportPDFView.as_view(), name="revenue-report-pdf"),
    path("api/reports/property/<int:property_id>/monthly-revenue/pdf",
         PropertyRevenueMonthlyPDFView.as_view(), name="property-monthly-revenue-pdf"),
    path("api/reports/property/<int:property_id>/occupancy/pdf",
         OccupancyRatePDFView.as_view(), name="occupancy-rate-pdf"),
]

# conciergerie/ota_webhooks/urls.py

urlpatterns += [
    path("webhooks/airbnb/", airbnb_webhook, name="airbnb-webhook"),
    path("webhooks/booking/", booking_webhook, name="booking-webhook"),
]

# --- Documentation OpenAPI avec drf-spectacular ---

urlpatterns += [
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
]


urlpatterns += [
    # endpoints périodiques
    # conciergerie/urls.py
    path("api/today-checkins/", api_report.TodayCheckinsView.as_view(), name="today-checkins"),
    path("reservations/period/<str:period>/", ReservationPeriodAPIView.as_view(), name="resa-period"),
    path("tasks/period/<str:period>/", ServiceTaskPeriodAPIView.as_view(), name="task-period"),
]

##  endpoint pour les taches et reservations par periode
urlpatterns += [
    path("api/dashboard/", co_api_dashboard.DashboardWeekAPIView.as_view(), name="api-dashboard"),
    # conciergerie/urls.py
    path("api/dashboard/week/", co_api_dashboard.DashboardWeekAPIView.as_view(), name="api-dashboard-week"),
    path("api/dashboard/month/", co_api_dashboard.DashboardMonthAPIView.as_view(), name="api-dashboard-month"),
    path("api/dashboard/quarter/", co_api_dashboard.DashboardQuarterAPIView.as_view(), name="api-dashboard-quarter"),
    path("api/dashboard/year/", co_api_dashboard.DashboardYearAPIView.as_view(), name="api-dashboard-year"),
]

## 

## some report api's 
# indicateurs cles 
urlpatterns += [
    # --- indicateurs clés ---
    path("api/kpi/available/", api_report.AvailableApartmentsAPIView.as_view(), name="kpi-available"),
    path("api/kpi/vacancy/", api_report.VacancyRateAPIView.as_view(), name="kpi-vacancy"),
    path("api/kpi/occupancy/", api_report.OccupancyRateAPIView.as_view(), name="kpi-occupancy"),
    path("api/kpi/active-bookings/", api_report.ActiveBookingsAPIView.as_view(), name="kpi-active"),
    path("api/kpi/revpar/", api_report.RevPARAPIView.as_view(), name="kpi-revpar"),
    path("api/kpi/avg-basket/", api_report.AvgBasketAPIView.as_view(), name="kpi-avg-basket"),
    path("api/kpi/gross-margin/", api_report.GrossMarginAPIView.as_view(), name="kpi-margin"),
    path("api/kpi/loyalty/", api_report.LoyaltyRateAPIView.as_view(), name="kpi-loyalty"),
    path("api/kpi/csat/", api_report.CSATAPIView.as_view(), name="kpi-csat"),
    path("api/kpi/avg-service-cost/", api_report.AvgServiceCostAPIView.as_view(), name="kpi-avg-cost"),
    path("api/kpi/portfolio-size/", api_report.PortfolioSizeAPIView.as_view(), name="kpi-portfolio"),
    path("api/kpi/avg-stay-duration/", api_report.AvgStayDurationAPIView.as_view(), name="kpi-avg-stay"),
    path("api/kpi/acceptance/", api_report.AcceptanceRateAPIView.as_view(), name="kpi-acceptance"),
    path("api/kpi/clv/", api_report.CLVAPIView.as_view(), name="kpi-clv"),
    path("api/kpi/cac/", api_report.CACAPIView.as_view(), name="kpi-cac"),
]


# --------------  DETAIL SUPPLY  -----------------
# single property full payload
urlpatterns += [
    path("apiplus/properties/<int:pk>/", co_api_views.PropertyDetailAPIView.as_view(),
     name="property-detail"),

    # reservations linked to ONE property (calendar & check-ins)
    path("api/reservations/property/<int:property_id>/",
        co_api_views.ReservationByPropertyListAPIView.as_view(),
        name="resa-by-property"),

    # revenue & occupancy dedicated to ONE property
    path("api/reports/property/<int:property_id>/revenue/",
        co_api_views.PropertyRevenueAPIView.as_view(),
        name="property-revenue"),

    path("api/reports/property/<int:property_id>/occupancy/",
        co_api_views.PropertyOccupancyAPIView.as_view(),
        name="property-occupancy"),
]

from conciergerie import api_property_public_views as api_appart

# --------------  DETAIL SUPPLY  -----------------
# single property full payload
#------------------------------------------------

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# urls.py (niveau projet)  
from rest_framework_simplejwt.views import (  
    TokenObtainPairView,  
    TokenRefreshView,  
    TokenVerifyView,  
)  
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView, SpectacularRedocView


urlpatterns = [
    path('', include('conciergerie.urls')),
    path("admin/", admin.site.urls),
    path('staff/', include('staff.urls')),
    # fullcalendar
    path('calendar/', include('fullcalendar.urls')),
    ## path('report/', include('slick_report.urls')),
    # SQL Explorer
    path('explorer/', include('explorer.urls')),
    # pandas Report 
    ##path('pandas/', include('pandas_report.urls')),
    # fullcalendar
    ## path('calendar/', include('fullcalendar.urls')),

]
""" 
# JWT Auth
# api/auth pour login/logout
# api/auth/registration pour creer un user
# pour obtenir un token : voici les urls
# refresh token et verify token
"""

urlpatterns += [  
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),  
    path('api/token/verify/', TokenVerifyView.as_view(), name='token_verify'),  
    ##
    # path('api/auth/', include('dj_rest_auth.urls')),
    path('api/auth/registration/', include('dj_rest_auth.registration.urls')),
]  

# Documentation automatique avec drf-spectacular
# https://drf-spectacular.readthedocs.io/en/latest/readme.html

urlpatterns += [
    # tes autres URLs...
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/schema/swagger-ui/', SpectacularSwaggerView.as_view(url_name='schema'), name='swagger-ui'),
    path('api/schema/redoc/', SpectacularRedocView.as_view(url_name='schema'), name='redoc'),
]


# Ajoutez ces lignes pour servir les fichiers média en mode développement

if settings.DEBUG:

    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0])

    # Serve static and media files from development server
    #urlpatterns += staticfiles_urlpatterns()

fullcalendar/urls.py
from django.urls import path, include
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework.routers import DefaultRouter
from fullcalendar import views 

app_name = "fullcalendar"


urlpatterns = [
    path('home/', views.home, name='calendar_home'),
    path('resa/', views.calendar_reservation, name='calendar_resa'),
    path('empl/', views.calendar_employee, name='calendar_empl'),
    ## path('api/v1/calendar/employee-tasks/', EmployeeTaskCalendarView.as_view(), name='employee_task_calendar'),
    ##
    path('cal/property/<int:property_id>', views.FullcalendarPropertyView.as_view(), name='calendar_property_resa'),
]

staff/urls.py
# conciergerie/urls.py  (ajout en fin de fichier)

from django.contrib import admin
from django.urls import path, include

from rest_framework.routers import DefaultRouter
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from staff.staff_dashboard_api_views import (
    EmployeeListAPIView,
    AbsenceListAPIView,
    AbsenceUpdateAPIView,
    TaskListAPIView,
    StaffOccupancyKPIView,
    TasksDelayKPIView,
    PendingLeavesKPIView,
    StaffCSATKPIView,
)

from staff import views as rh_views

app_name = "staff"


urlpatterns = [
    path('home/', rh_views.home , name='rh_home'),
]

#-----------------------------
# - API
#-----------------------------
#
urlpatterns += [
    # employees
    path('api/employees/', EmployeeListAPIView.as_view(), name='api-employee-list'),
    # absences
    path('api/absences/', AbsenceListAPIView.as_view(), name='api-absence-list'),
    path('api/absences/<int:pk>/', AbsenceUpdateAPIView.as_view(), name='api-absence-update'),
    # tasks
    path('api/tasks/', TaskListAPIView.as_view(), name='api-task-list'),
    # RH KPIs
    path('api/kpi/staff-occupancy/', StaffOccupancyKPIView.as_view(), name='kpi-staff-occupancy'),
    path('api/kpi/tasks-delay/', TasksDelayKPIView.as_view(), name='kpi-tasks-delay'),
    path('api/kpi/pending-leaves/', PendingLeavesKPIView.as_view(), name='kpi-pending-leaves'),
    path('api/kpi/staff-csat/', StaffCSATKPIView.as_view(), name='kpi-staff-csat'),
]

conciergerie/forms.py
# conciergerie/forms.py
import csv
import io
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class ReservationImportForm(forms.Form):
    csv_file = forms.FileField(
        label=_("Fichier CSV (séparateur virgule)"),
        help_text=_("Colonnes attendues : Date reservation,Date arrive Arrivée au plus tard le,Nb Nuits,Nom Voyageur,Property Logement,Devise,Montant Versé,Frais de service,Frais de paiement rapide,Frais de ménage,Frais pour le linge de maison,Revenus bruts")
    )

    def clean_csv_file(self):
        f = self.cleaned_data["csv_file"]
        if not f.name.lower().endswith(".csv"):
            raise ValidationError(_("Le fichier doit avoir l'extension .csv"))
        return f

    def read(self):
        """Return list[dict] ready for importer"""
        file = self.cleaned_data["csv_file"]
        decoded_file = file.read().decode("utf-8-sig")
        reader = csv.DictReader(io.StringIO(decoded_file))
        return list(reader)



class CheckoutInventoryForm(forms.Form):
    pass

conciergerie/templates/menus/main_menu.html
 {% load static %}
 <nav class="navbar navbar-default navbar-expand-lg navbar-light bg-dark">
        <div class="container">
            <a class="navbar-brand pt-1" href="{% url 'conciergerie:home' %}" >Happy Bee</a>
            <img stye="height:50%" class="pr-2" src="{% static 'img/Happy_Bee_100x100.jpg' %}"  > 

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" 
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" 
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            
            <div class="collapse navbar-collapse"> 
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" 
                        aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Rechercher</button>
                </form>
            </div>
        </div>
        
        <div class="container">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                   {# Header contains the main_navigation block #}
                {# "home/menus/main_menu.html" with parent=site_root calling_page=self #}
                <ul class="nav navbar navbar-right">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" 
                        id="navbarDropdown" role="button" data-toggle="dropdown" 
                        aria-expanded="false"> Service
                        </a>
                        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="/admin/devis/" target="_blanc">Devis</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/invoice/" target="_blanc">Facture</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/customer/customer/" target="_blanc">Client</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/product/" target="_blanc">Catalog produit</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/profile/" target="_blanc">Profile</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/shop/" target="_blanc">Store shopy</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/project/project/" target="_blanc">Projet</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/auth/" target="_blanc">Compte utilisateurs</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" 
                        id="navbarDropdown" role="button" data-toggle="dropdown" 
                        aria-expanded="false"> admin
                        </a>
                        <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="#">A propos</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="/admin/login">Connexion</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link " href="#" 
                        id="navbarDropdown" role="button" data-toggle="dropdown" 
                        aria-expanded="false">
                        </a>
                    </li>
                </ul>
           </div>
        </div>
    </nav>

conciergerie/templates/menus/nav_menu.html
<nav id="sidebar" class="mt-5 col-md-3 col-lg-2 d-md-block bg-light sidebar sidebar-collapsed">
    <div class="pt-3">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link active" href="#">
                    <i class="bi bi-house-door"></i> Tableau de bord
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'conciergerie:property_list' %}">
                    <i class="bi bi-building"></i> propriétés
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'conciergerie:home' %}">
                    <i class="bi bi-people"></i> Reservations
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'fullcalendar:calendar_empl' %}" target="blank">
                    <i class="bi bi-calendar-event"></i> Planning des employées
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'fullcalendar:calendar_resa' %}" target="blank">
                    <i class="bi bi-calendar-event"></i> Planning des reservations
                </a>
            </li>
            
            <li class="nav-item">
                <a class="nav-link" href="/service/api/" target="blank">
                    <i class="bi bi-file-earmark-text"></i> API router
                </a>
            </li>
        </ul>
    </div>
</nav>


{% block extra_css %}
    <style>
        .sidebar{
            top: 20%;
        }


        .sidebar-trigger {
            position: fixed;
            left: 60px;
            top: 50%;
            transform: translateY(-50%);
            width: 20px;
            height: 40px;
            background-color: #f8f9fa;
            border-radius: 0 5px 5px 0;
            display: flex;
            align-items: center;
            justify-content: center;
            cursor: pointer;
            z-index: 1000;
        }

        .sidebar-collapsed .nav-link span {
            display: none;
        }

        .sidebar-expanded .nav-link span {
            display: inline;
        }
    </style>
{% endblock %}

conciergerie/templates/menus/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>